server:
  port: 8081
spring:
  application:
    name: spring-ai-mcp-server-example
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://localhost:3306/mcp_sample?useUnicode=true&characterEncoding=utf8&serverTimeZone=UTC
    username: root
    password:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  ai:
    mcp:
      server:
        name: mcp-server
        version: 1.0.0
        enabled: true
        type: SYNC

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: info
    jdbc:
      audit: OFF
      resultset: OFF
      resultsettable: OFF
      sqlonly: INFO
      sqltiming: OFF
      connection : OFF
    org.springframework.ai: DEBUG