INSERT INTO inquiries (question, answer, reg_date, mod_date) VALUES
  ('Is this product in stock?', 'Yes, it is currently in stock.', NOW(), NOW()),
  ('How long does shipping take?', 'Shipping usually takes 2-3 business days.', NOW(), NOW()),
  ('What colors are available?', 'We currently have black, white, and silver available.', NOW(), NOW()),
  ('How do I choose the right size?', 'Please refer to the size guide on the product page.', NOW(), NOW()),
  ('When will you have a sale?', 'There are no sales scheduled at the moment.', NOW(), NOW()),
  ('How can I request after-sales service?', 'Please contact our customer service with your purchase details.', NOW(), NOW()),
  ('Can I get a product manual?', 'Yes, we can email it to you.', NOW(), NOW()),
  ('Please compare this model with another one.', 'Please let us know which model you\'d like to compare it with.', NOW(), NOW()),
  ('Is gift wrapping available?', 'Yes, we offer gift wrapping services.', NOW(), NOW()),
  ('Is there a discount for bulk orders?', 'Please inquire separately for bulk order discounts.', NOW(), NOW()),
  ('What is the weight of this product?', 'This product weighs 1.5kg.', NOW(), NOW()),
  ('Is it waterproof?', 'Yes, it supports basic water resistance.', NOW(), NOW()),
  ('Is this an authentic product?', 'Yes, all our products are 100% authentic.', NOW(), NOW()),
  ('Can I buy spare parts separately?', 'Some spare parts are available for separate purchase. Please contact customer service.', NOW(), NOW()),
  ('Is there an age limit for using this product?', 'We recommend this product for ages 14 and above.', NOW(), NOW()),
  ('What is the maximum load capacity?', 'It can support a maximum load of 100kg.', NOW(), NOW()),
  ('I need help with the assembly.', 'Please refer to the assembly instructions included with the product. We also have a video tutorial available.', NOW(), NOW()),
  ('What is the warranty period?', 'The warranty period is 1 year from the date of purchase.', NOW(), NOW()),
  ('How do I replace the battery?', 'The battery replacement instructions are detailed in the user manual.', NOW(), NOW()),
  ('Are there any other colors planned for release?', 'Currently, there are no plans for additional color releases.', NOW(), NOW()),
  ('What material is this product made of?', 'It is made of aluminum alloy.', NOW(), NOW()),
  ('How should I clean this product?', 'You can clean it with a soft cloth.', NOW(), NOW()),
  ('I bought this online and want to exchange it.', 'You can submit an exchange request through your order history on our website.', NOW(), NOW()),
  ('Can I get a receipt?', 'Yes, you can print a receipt from your order details.', NOW(), NOW()),
  ('Where is this product manufactured?', 'This product is manufactured in Korea.', NOW(), NOW()),
  ('Do you have a price match guarantee?', 'Yes, we offer a price match guarantee.', NOW(), NOW()),
  ('When will the out-of-stock item be available again?', 'The restock date is currently uncertain. Please sign up for restock notifications on the product page.', NOW(), NOW()),
  ('I want to change my payment method.', 'It is not possible to change the payment method after the order has been placed.', NOW(), NOW()),
  ('Until when can I cancel my order?', 'You can cancel your order before it is shipped.', NOW(), NOW()),
  ('I want to change my shipping address.', 'You can change your shipping address if the order hasn\'t been shipped yet. Please contact customer service.', NOW(), NOW()),
  ('Are there any precautions I should take when using this product?', 'Please read the user manual carefully before use.', NOW(), NOW()),
  ('What is your customer service phone number?', 'Our customer service phone number is 000-0000-0000.', NOW(), NOW()),
  ('Are there any compatible accessories for this product?', 'Yes, there are several compatible accessories. Please check the product details page.', NOW(), NOW()),
  ('Do you ship internationally?', 'We do not currently offer international shipping.', NOW(), NOW()),
  ('Where can I see the product reviews?', 'You can find the reviews at the bottom of the product details page.', NOW(), NOW()),
  ('If I order today, when will I receive it?', 'If you order today, you should receive it tomorrow (delivery times may vary by region).', NOW(), NOW()),
  ('What is the energy efficiency rating of this product?', 'This product has an energy efficiency rating of A.', NOW(), NOW()),
  ('What is the free repair period?', 'The free repair period is 6 months from the date of purchase.', NOW(), NOW()),
  ('I think there is a defect in the product.', 'We apologize for the inconvenience. Please contact customer service with photos of the defect, and we will handle it promptly.', NOW(), NOW()),
  ('When will I receive the free gift?', 'The free gift will be shipped with your order.', NOW(), NOW()),
  ('What is the minimum order quantity for this product?', 'The minimum order quantity is 1.', NOW(), NOW()),
  ('Can I get a sample?', 'We are unable to provide samples at this time.', NOW(), NOW()),
  ('Is this product environmentally friendly?', 'Yes, it is made with environmentally friendly materials.', NOW(), NOW()),
  ('Is it safe for children to use?', 'Yes, it is manufactured in compliance with safety standards.', NOW(), NOW()),
  ('What are the advantages of this product?', 'It is durable and easy to use.', NOW(), NOW()),
  ('Is this product discontinued?', 'No, this product is currently on sale.', NOW(), NOW()),
  ('Are there any update plans?', 'There are no update plans at the moment.', NOW(), NOW()),
  ('Are there any events related to this product?', 'There are no ongoing events related to this product.', NOW(), NOW()),
  ('What is the resolution?', 'The resolution is 1920x1080.', NOW(), NOW()),
  ('What is the screen size?', 'The screen size is 27 inches.', NOW(), NOW()),
  ('I\'m curious about how this product works.', 'The operating principle is as follows: [brief explanation].', NOW(), NOW()),
  ('What is the noise level?', 'The noise level during operation is below 30dB.', NOW(), NOW()),
  ('What is the power consumption?', 'The maximum power consumption is 50W.', NOW(), NOW()),
  ('Can I connect this to [device name]?', 'Yes, it is compatible with [device name].', NOW(), NOW()),
  ('Do you have a physical store where I can see the product?', 'Yes, we have physical stores located at [list of locations].', NOW(), NOW()),
  ('What are the system requirements?', 'The system requirements are [list of requirements].', NOW(), NOW()),
  ('Is there a student discount?', 'Yes, we offer a student discount. Please provide your student ID for verification.', NOW(), NOW()),
  ('Can I return the product if I don\'t like it?', 'Yes, you can return the product within 30 days of purchase, provided it is in its original condition.', NOW(), NOW()),
  ('Do you offer installation services?', 'Yes, we offer installation services for an additional fee. Please contact us for details.', NOW(), NOW()),
  ('What kind of warranty do you offer?', 'We offer a limited warranty that covers manufacturing defects for one year.', NOW(), NOW())
;